### ISSUE TITLE
这个web页面，能不能增加左右方向键进行上一章，下一章的切换？

### ISSUE THREAD

**Issue by muzhi621** [Celeter/web-yuedu3#2]
这个web页面，能不能增加左右方向键进行上一章，下一章的切换？

**Comment by FanchangWang** [comment]
相关功能已提交  [pr#4](https://github.com/Celeter/web-yuedu3/pull/4)

**Comment by FanchangWang** [comment]
功能已经合并，下载最新版阅读 3.0 就可以了
