### ISSUE TITLE
20201106版本的SetIp为什么空了？

### ISSUE THREAD

**Issue by H-olxx** [Celeter/web-yuedu3#29]

**Comment by Celeter** [comment]
![image](https://user-images.githubusercontent.com/48249130/106243875-1173cf80-6245-11eb-8828-b5ede3114d8b.png)
master版是打包进阅读3.0的版本，不能设置ip，slave版可以设置

**Comment by H-olxx** [comment]
查到了，谢谢，大佬的软件是真的优雅

**Comment by H-olxx** [comment]
为什么要用两个分支来区分版本，而不是用两个打包命令，用变量控制？是github的自动部署不支持吗？

**Comment by Celeter** [comment]
代码不一样，没设置标志，懒得改了

**Comment by H-olxx** [comment]
失敬失敬🤣
