### ISSUE TITLE
老哥，7.4号的这个dist解压打开后，直接显示连接后端，不能输入后端ip和端口？希望能改一下，我研究了一下，不熟悉，没找到怎么解决

### ISSUE THREAD

**Issue by muzhi621** [Celeter/web-yuedu3#5]

**Comment by FanchangWang** [comment]
这个不是直接使用的，已经打包进最新版阅读 3.0 版本里面了。
如果你要直接使用的话，可以配置个 nginx 代理。或者直接下载源码，在 vue.config.js 里面加上 proxy 代理配置

**Comment by muzhi621** [comment]
还是不会，
![image](https://user-images.githubusercontent.com/41742756/86730576-4201db00-c061-11ea-9f82-00519993490d.png)改成这样的要改哪里，我百度了一个proxy代理加进去// vue.config.js
module.exports = {
  publicPath: "./",
  productionSourceMap: false,
  devServer : {
        proxy : {
            '^/osce2' : {
                target : 'http://localhost:8081', // 设置接口域名和端口号
                changeOrigin : true, // 跨域
                pathRewrite : {
                    '^/osce2' : '/osce2'
                }
            },
        }
    }
};
，打包后，还是
![image](https://user-images.githubusercontent.com/41742756/86730705-68277b00-c061-11ea-8a7d-e78ead4bb716.png)

**Comment by FanchangWang** [comment]
`vue.config.js` 配置 `proxy ` 仅适用于调试模式 ` yarn serve`

你要打包使用的话，需要 `nginx` 配置转发

**Comment by muzhi621** [comment]
能给个怎么解决不，nginx怎么配置，然后加在哪里？谢谢谢谢，这个不懂

**Comment by muzhi621** [comment]
就是做到像前一版那种，打包成dist后，我可以自己输入ip和端口，这个得怎么搞

**Comment by muzhi621** [comment]
放在coding上一个简单的静态托管，每次输入IP和端口，上一版的dist，对比了这次改动的地方，好像没有影响，所以也找不到问题在哪了

**Comment by FanchangWang** [comment]
> 放在coding上一个简单的静态托管，每次输入IP和端口，上一版的dist，对比了这次改动的地方，好像没有影响，所以也找不到问题在哪了

你这完全没必要啊，《阅读 3.0》APP 里面已经集成了，你启动『WEB 服务』后，直接使用就行了，比如 <http://192.168.1.6:1122/new/bookshelf.html#/>

**Comment by muzhi621** [comment]
![image](https://user-images.githubusercontent.com/41742756/86738338-93ad6400-c067-11ea-9464-9131e6d06649.png)
以前都是那样用的，习惯了，这个我点不进，换个浏览器好像可以，但是进去后列表智友单列，是不是我的电脑的原因，所以只能寻求你们的帮助了，能再发布一个release就好了，抱拳

**Comment by FanchangWang** [comment]
- 设置 IP 的功能很早就去除掉了，具体见 [commit#31aaf7](https://github.com/Celeter/web-yuedu3/commit/a7c9b4e777533b7c0cf58c256a61a9f50431aaf7)，之后发布的版本都不会带这个功能了，你可以继续使用老的版本
- nginx 转发不适合你，那个无法使用 `coding` 静态托管
- 你浏览器没有 `CSS` 样式，可以尝试清除一下浏览器缓存试试

**Comment by muzhi621** [comment]
行吧，好的谢谢

**Comment by Celeter** [comment]
> 行吧，好的谢谢

slave分支可以设置ip，已经在release中发布
